version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - webshop_network
    env_file: 
      - .env
      

  db:
    image: mysql:latest
    container_name: mysql-database
    restart: always
    env_file:
      - .env  
    volumes:
      - ./data:/var/lib/mysql
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro 
    ports:
      - "3306:3306"
    command: --lower_case_table_names=2
    networks:
      - webshop_network


  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: "listen --api-key ${STRIPE_SECRET_KEY} --forward-to http://host.docker.internal:3000/api/payment/webhook"
    env_file:
      - .env  
    networks:
      - webshop_network  

networks:
  webshop_network:
