@startuml Account

|User|
:Sign In Method;

if (Sign in with Google?) then (yes)
    :Google Login;
    if (Valid Google sign in?) then (yes)
        :Set Account State;
    else (no)
        :Error indication; 
        stop
    endif
else (no)
    if (Sign in with Own Credentials?) then (yes)
        :Own Credentials Login;
    else (no)
        :Show Create Account Screen;
        if (Account Created?) then (yes)
            :Return to Login;
        else (no)
            :Error indication;
            stop
        endif
    endif
    
    if (Credentials Valid?) then (yes)
        :Set Account State;
    else (no)
        :Error indication; 
        stop
    endif
endif

@enduml
