@startuml interface

class ItemImagesInterface {
  url: string
  baseUrl: string
}

class UniqueItemInterface {
  id: string
  name: string
  imagePoster: string
  price: number
  galleryImages: List<ItemImagesInterface>
  similarImages: List<string>
  clothingSizes: List<string>
  itemColor: string | { text: string, code: string }
  itemCategory: string
}

class StripPaymentInterface {
  title: string
  imageUrl: string
  price: number
  quantity: number
}

class FilteredItemDataInterface extends UniqueItemInterface {
  uniqueItem: UniqueItemInterface
  itemColorCode: string
  itemCategory: string
}


class SearchInputInterface {
  title: string
  imagePoster: string
}


class FilteredProductData {
  productItems: List<FilteredItemDataInterface>
  filterOptions: FilterOptions
}

class ColorOptions {
  text: string
  code: string
}

class FilterOptionsInterface {
  color: List<ColorOptions>
  categories: List<string>
}

class CartItemInterface {
  title: string
  imageUrl: string
  size: string
  quantity: number
  price: number
}

class UserDataInterface {
  name?: string
  email?: string
  initialsImageUrl?: string
}

class AccountContextInterface {
  user: UserDataInterface | null
  setUser(userData: UserDataInterface | null): void
}

UniqueItemInterface -- ItemImagesInterface
UniqueItemInterface -- SearchInputInterface
FilteredItemDataInterface -- ItemImagesInterface
FilteredProductData -- FilteredItemDataInterface
FilteredProductData -- FilterOptionsInterface
FilterOptionsInterface -- ColorOptions
AccountContextInterface -- UserDataInterface
UniqueItemInterface -- CartItemInterface
CartItemInterface -- StripPaymentInterface

@enduml